name: Generate Snake with Date

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: herian-22
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#1DA1F2

      - name: Add timestamp
        run: |
          mkdir -p ./dist
          sudo chmod -R 777 ./dist
          echo "ðŸ—“ï¸ $(date '+%B %Y')" > ./dist/date.txt

      - name: Update date in README
        run: |
          CURRENT_DATE=$(date +"%B %Y")
          sed -i "s|<span id=\"date\">.*</span>|<span id=\"date\">${CURRENT_DATE}</span>|" README.md

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
  
      - name: Update date in README
        run: |
          CURRENT_DATE=$(date +"%B %Y")
          echo "Updating date to $CURRENT_DATE"
          sed -i 's|<span id="date">[^<]*</span>|<span id="date">'"$CURRENT_DATE"'</span>|' README.md
          git add README.md
          git commit -m "Update date automatically: ${CURRENT_DATE}" || echo "No changes"
          git push

